// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use uuid::Uuid;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(creditid))]
pub struct Allocatedcredit {
    pub creditid: i32,
    pub userid: i64,
    pub credits: i32,
    pub expireat: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Generation {
    pub userid: Option<i64>,
    pub id: i64,
    pub status: Option</* TODO: unknown type Nullable<GenerationStatus> */>,
    pub createdat: NaiveDateTime,
    pub finishedon: Option<NaiveDateTime>,
    pub jobid: Option<Uuid>,
    pub creditsused: Option<i16>,
    pub category: Option<String>,
    pub options: Option<String>,
    pub displayname: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Supportticketmessage {
    pub id: i32,
    pub ticketid: i32,
    pub message: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Supportticket {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub wau: Option</* TODO: unknown type Nullable<Supportwhoareyou> */>,
    pub state: /* TODO: unknown type Supportticketstate */,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(userid))]
pub struct User {
    pub userid: i64,
    pub username: String,
    pub email: String,
    pub emailverified: Option<bool>,
    pub bcryptpass: Option<Vec<u8>>,
    pub createdat: Option<NaiveDateTime>,
    pub supportprivilege: Option<bool>,
}

